// Corrigé de l'exercice : servi uniquement à l'animateur (mot de passe vérifié), jamais présent dans les pages élèves.
module.exports = `<strong>Coupable :</strong> Julien MOREAU (DSI), recruté par ingénierie sociale (pression financière + flatterie - leviers Espèces et Vanité).<br> <strong>Vecteur initial :</strong> mail spearphishing (faux recruteur Thales), pièce jointe .docm piégée.<br> <strong>Canal de sortie :</strong> passerelle BX-GATEWAY-07 vers l'IP 185.220.101.47 (à distinguer de 10.42.6.11 = interne légitime et 20.42.73.18 = Azure NTP légitime).<br> <strong>Conséquence la plus grave : le boîtier BX-4216 compromis.</strong> Dans la nuit du 15 au 16 mai, les boîtiers du lot S42 sont branchés sur le banc de contrôle, relié à la passerelle. Le 16 mai à 02h31, grâce à la porte dérobée ouverte avec l'accès DSI de MOREAU, l'attaquant envoie par la télémaintenance un firmware modifié au BX-4216, le boîtier destiné au programme classé Thales THA-REF-28471 (ligne Wazuh, 2 Mo vers 10.42.6.116 dans le journal de la passerelle). Le 17 mai, N. BRUNET mesure +40 % de consommation à 33 °C (atelier à température normale) : la chaleur n'explique rien. Le 19 mai, sous la pression du délai Thales, le rapport de conformité du Montage attribue l'écart à la chaleur et valide l'expédition : un composant piégé allait partir chez un client défense. Préconisations attendues : bloquer l'expédition, reflasher et auditer tout le lot, séparer la télémaintenance du banc de contrôle, ne jamais valider une conformité sur une hypothèse non vérifiée.<br>
 <strong>Cause racine organisationnelle :</strong> absence de revue de code et de contrôle des changements sur le programme de supervision de la passerelle BX-GATEWAY-07, ayant permis l'introduction d'une porte dérobée par modification d'une ligne de code le 9 mai (voir onglet Programmation), détectée par le contrôle d'intégrité Wazuh FIM.<br> <strong>Fausses pistes à écarter</strong> (chacune a un mobile ou une occasion, aucune n'a les trois : mobile, accès et traces) :<br>
- Karim BENYOUCEF : dettes, comme MOREAU, mais aucun accès informatique et aucune trace dans les journaux. L'attaquant cible une personne fragile qui a les clés.<br>
- Farid HADDAD : en Chine le 2 mai et contacts SinoBoard, mais le 2 mai tout se passe sur le poste de MOREAU ; dossier SinoBoard jamais signé ni déployé (mail Achats, note Achats).<br>
- Camille ROUSSEAU : idéologie (collectif, site militant dans Wazuh), mais aucun accès technique ; absente depuis le 15 mai.<br>
- Thomas VASSEUR : trou de CV et accès au local technique, mais aucune trace informatique ; le code a été modifié à distance, depuis le poste de MOREAU.<br>
- Nathalie BRUNET : connexion à 22h01 le 17 mai, expliquée dans son mail (rapport qualité).<br>
- Marc DURAND : demande de VPN pour le 21 et 22 mai (après les faits, motif personnel) ; son quiz Facebook est le piège pédagogique sur les données personnelles.<br>
- Faux technicien (P. THIERRY) : prestataire TéléMaint Centre, ticket TICK-4147 (mail des Services généraux) ; le 6 mai, seule une coupure d'alimentation apparaît, aucune modification du code.<br>
- Balayage de ports du 12 mai (Critique dans Wazuh) : scan trimestriel annoncé par la DSI le 11 mai (Sigma-Tech, 10.42.1.30). Fin de l'histoire dans la boîte de MOREAU : le rapport Sigma-Tech du 13 mai signale le port 443 ouvert sur la passerelle (la porte dérobée du 9 mai) ; MOREAU a fait mettre à jour l'imprimante (17 mai) mais n'a rien fait pour la passerelle.<br>
- Antivirus de la comptabilité (13 mai) : campagne Emotet de fausses factures, bloquée, sans lien avec l'attaque. Exercice de sensibilisation : S. LEBRUN demande à l'audit si elle peut désactiver l'antivirus (bonne réponse : non, transmettre à la DSI).<br>
- Fausses pistes faciles des boîtes employés (accroche et preuve dans la même boîte) : VASSEUR (trou de CV = formation AFPA 2023-2024), DURAND (annonce leboncoin = restes de sa rénovation), BENYOUCEF (virement de 1 500 € = prime d'intéressement ELECARM), ROUSSEAU (le collectif lui demande des infos, elle refuse), HADDAD (cadeau de SinoBoard, qu'il renvoie en citant la charte éthique).<br>
- Clé USB « DIAG » (boîte de P. THIERRY uniquement), trouvée le 19 mai : outils de diagnostic de TéléMaint oubliés le 6 mai. Exercice de sensibilisation : ne pas la brancher, la remettre à la DSI. Elle permet d'écarter le choix « clé USB » du QCM.<br>
- Les actions des élèves (portail de phishing, clé USB branchée, antivirus désactivé) apparaissent en direct dans Wazuh sur « POSTE-AUDIT » ou « WS-COMPTA » : le SIEM voit tout.<br>
- 20.42.73.18 : Azure NTP, ajouté officiellement le 22 avril (onglet Programmation).<br>
- Antoine ROBERT : accès révoqués à son départ (mail RH et fiche de sortie).<br>
- TechIndus Solutions : simple note de vigilance, aucune preuve technique.`;
